# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11recommender.proto\x12\x04main\"\x1f\n\x0cRecommendReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\"\n\x0cRecommendRes\x12\x12\n\nproduct_id\x18\x01 \x03(\x05\"A\n\nCommentReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x0e\n\x06rating\x18\x03 \x01(\x05\"#\n\x10NonQueryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9c\x01\n\x16RecommenderBaseComment\x12\x36\n\nAddComment\x12\x10.main.CommentReq\x1a\x16.main.NonQueryResponse\x12J\n LisRecommendedProductIDsByUserID\x12\x12.main.RecommendReq\x1a\x12.main.RecommendResB\x04Z\x02/.b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommender_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002/.'
  _RECOMMENDREQ._serialized_start=27
  _RECOMMENDREQ._serialized_end=58
  _RECOMMENDRES._serialized_start=60
  _RECOMMENDRES._serialized_end=94
  _COMMENTREQ._serialized_start=96
  _COMMENTREQ._serialized_end=161
  _NONQUERYRESPONSE._serialized_start=163
  _NONQUERYRESPONSE._serialized_end=198
  _RECOMMENDERBASECOMMENT._serialized_start=201
  _RECOMMENDERBASECOMMENT._serialized_end=357
# @@protoc_insertion_point(module_scope)
