# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11recommender.proto\x12\x0brecommender\"\x1f\n\x0cRecommentReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"\"\n\x0cRecommentRes\x12\x12\n\nproduct_id\x18\x01 \x03(\x05\"A\n\nCommentReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\x12\x0e\n\x06rating\x18\x03 \x01(\x05\"7\n\x10\x44\x65leteCommentReq\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x12\n\nproduct_id\x18\x02 \x01(\x05\"#\n\x10NonQueryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd8\x02\n\x16RecommenderBaseComment\x12\x46\n\nAddComment\x12\x17.recommender.CommentReq\x1a\x1d.recommender.NonQueryResponse\"\x00\x12I\n\rUpdateComment\x12\x17.recommender.CommentReq\x1a\x1d.recommender.NonQueryResponse\"\x00\x12O\n\rDeleteComment\x12\x1d.recommender.DeleteCommentReq\x1a\x1d.recommender.NonQueryResponse\"\x00\x12Z\n LisRecommendedProductIDsByUserID\x12\x19.recommender.RecommentReq\x1a\x19.recommender.RecommentRes\"\x00\x42\x04Z\x02/.b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommender_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\002/.'
  _RECOMMENTREQ._serialized_start=34
  _RECOMMENTREQ._serialized_end=65
  _RECOMMENTRES._serialized_start=67
  _RECOMMENTRES._serialized_end=101
  _COMMENTREQ._serialized_start=103
  _COMMENTREQ._serialized_end=168
  _DELETECOMMENTREQ._serialized_start=170
  _DELETECOMMENTREQ._serialized_end=225
  _NONQUERYRESPONSE._serialized_start=227
  _NONQUERYRESPONSE._serialized_end=262
  _RECOMMENDERBASECOMMENT._serialized_start=265
  _RECOMMENDERBASECOMMENT._serialized_end=609
# @@protoc_insertion_point(module_scope)
